package Veduta::Model::VedutaDB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Veduta::Schema',
    
    connect_info => {
        dsn => 'dbi:Pg:dbname=veduta',
        user => 'vedutista',
        password => '',
    }
);

=head1 NAME

Veduta::Model::VedutaDB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Veduta>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Veduta::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

=head1 AUTHOR

GIS user

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
